import { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextMart | product",
  description: "Generated by create next app",
};

const ProductDetail = ({ params }: { params: { id: string } }) => {
  return (
    <div>
      <h1>This is {params.id} ProductDetail component</h1>
    </div>
  );
};

export default ProductDetail;
